name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:28

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        persist-credentials: false
    - name: Compile
      run: rebar3 compile
    - name: Compile Example
      working-directory: ./examples/demo_app/
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do xref, eunit, ct, lint
    - name: Run Examples
      working-directory: ./examples/demo_app/
      run: rebar3 ct
